var CookieConstants = {
  COOKIES_RECEIVED: "COOKIES_RECEIVED",
  COOKIE_RECEIVED: "COOKIE_RECEIVED",
  FETCH_COOKIES: "FETCH_COOKIES",
  CLEAR_COOKIES: "CLEAR_COOKIES",
  CLEAR_COOKIE: "CLEAR_COOKIE"
};

module.exports = CookieConstants;
