var ExerciseConstants = {
  EXERCISES_RECEIVED: "EXERCISES_RECEIVED",
  EXERCISE_RECEIVED: "EXERCISE_RECEIVED",
  REMOVE_FIRST_EXERCISE: "REMOVE_FIRST_EXERCISE"
};

module.exports = ExerciseConstants;
