var ModalConstants = {
  TOGGLE_MODAL_DISPLAY: "TOGGLE_MODAL_DISPLAY",
  ADD_MODAL: "ADD_MODAL",
  REMOVE_MODAL: "REMOVE_MODAL",
  HIDE_MODALS: "HIDE_MODALS",
  DISPLAY_MODAL: "DISPLAY_MODAL",
  HIDE_MODAL: "HIDE_MODAL"
};

module.exports = ModalConstants;
