json.extract! @user,
              :bio,
              :id,
              :fname,
              :lname,
              :current_course_id,
              :current_language_id,
              :email,
              :username,
              :streak_length,
              :points,
              :hometown,
              :enrolled_courses,
              :completions
