json.extract! @user,
              :bio,
              :id,
              :fname,
              :lname,
              :current_course_id,
              :current_language_id,
              :email,
              :username,
              :streak_length,
              :points,
              :uid,
              :hometown,
              :enrolled_courses,
              :completions
json.profile_pic_url asset_path(@user.profile_pic.url(:original))
